using LeekLog.Abstractions.Entites;
using LeekLog.Data.Abstractions.Stores;

namespace LeekLog.Data;

public interface IMetaDataInitializer
{
    Task InitMetaDataAsync(CancellationToken ct = default);
}

public class MetaDataInitializer : IMetaDataInitializer
{
    private readonly IExerciseStore _exerciseStore;

    public MetaDataInitializer(IExerciseStore exerciseStore)
    {
        _exerciseStore = exerciseStore;
    }

    public async Task InitMetaDataAsync(CancellationToken ct = default)
    {
        List<ExerciseEntity> allExercises = await _exerciseStore.GetAllAsync(ct);

        List<string> requiredExercises = GetAllExercises();

        List<ExerciseEntity> missingExercises = requiredExercises
            .Except(allExercises.Select(o => o.Title))
            .Select(o => new ExerciseEntity
            {
                Title = o
            })
            .ToList();

        await _exerciseStore.SaveAllAsync(missingExercises, ct);
    }

    private static List<string> GetAllExercises()
    {
        return new List<string>
        {
            "Air Squat",
            "Assisted Bar Dip",
            "Back Extension",
            "Band External Shoulder Rotation",
            "Band Internal Shoulder Rotation",
            "Band Pull-Apart",
            "Banded Side Kicks",
            "Bar Dip",
            "Bar Hang",
            "Barbell Curl",
            "Barbell Front Raise",
            "Barbell Hack Squat",
            "Barbell Lunge",
            "Barbell Lying Triceps Extension",
            "Barbell Preacher Curl",
            "Barbell Rear Delt Row",
            "Barbell Row",
            "Barbell Shrug",
            "Barbell Standing Triceps Extension",
            "Barbell Upright Row",
            "Barbell Walking Lunge",
            "Barbell Wrist Curl",
            "Barbell Wrist Curl Behind the Back",
            "Barbell Wrist Extension",
            "Behind the Neck Press",
            "Belt Squat",
            "Bench Dip",
            "Bench Press",
            "Block Snatch",
            "Body Weight Lunge",
            "Bodyweight Curl",
            "Box Squat",
            "Bulgarian Split Squat",
            "Cable Chest Press",
            "Cable Close Grip Seated Row",
            "Cable Crunch",
            "Cable Curl With Bar",
            "Cable Curl With Rope",
            "Cable Lateral Raise",
            "Cable Pull Through",
            "Cable Rear Delt Row",
            "Cable Wide Grip Seated Row",
            "Chair Squat",
            "Chin-Up",
            "Clamshells",
            "Clean",
            "Clean and Jerk",
            "Close-Grip Bench Press",
            "Close-Grip Feet-Up Bench Press",
            "Close-Grip Push-Up",
            "Concentration Curl",
            "Crunch",
            "Dead Bug",
            "Deadlift",
            "Decline Bench Press",
            "Deficit Deadlift",
            "Dumbbell Chest Fly",
            "Dumbbell Chest Press",
            "Dumbbell Curl",
            "Dumbbell Deadlift",
            "Dumbbell Decline Chest Press",
            "Dumbbell Floor Press",
            "Dumbbell Frog Pumps",
            "Dumbbell Front Raise",
            "Dumbbell Horizontal External Shoulder Rotation",
            "Dumbbell Horizontal Internal Shoulder Rotation",
            "Dumbbell Lateral Raise",
            "Dumbbell Lunge",
            "Dumbbell Lying Triceps Extension",
            "Dumbbell Preacher Curl",
            "Dumbbell Pullover",
            "Dumbbell Rear Delt Row",
            "Dumbbell Romanian Deadlift",
            "Dumbbell Row",
            "Dumbbell Shoulder Press",
            "Dumbbell Shrug",
            "Dumbbell Squat",
            "Dumbbell Standing Triceps Extension",
            "Dumbbell Wrist Curl",
            "Dumbbell Wrist Extension",
            "Eccentric Heel Drop",
            "Face Pull",
            "Farmers Walk",
            "Fat Bar Deadlift",
            "Feet-Up Bench Press",
            "Fire Hydrants",
            "Floor Back Extension",
            "Floor Press",
            "Frog Pumps",
            "Front Hold",
            "Front Squat",
            "Glute Bridge",
            "Goblet Squat",
            "Good Morning",
            "Gripper",
            "Hack Squat Machine",
            "Half Air Squat",
            "Hammer Curl",
            "Hang Clean",
            "Hang Power Clean",
            "Hang Power Snatch",
            "Hang Snatch",
            "Hanging Knee Raise",
            "Hanging Leg Raise",
            "Hanging Sit-Up",
            "Heel Raise",
            "High to Low Wood Chop with Band",
            "Hip Abduction Against Band",
            "Hip Abduction Machine",
            "Hip Adduction Machine",
            "Hip Thrust",
            "Hip Thrust Machine",
            "Hip Thrust With Band Around Knees",
            "Horizontal Wood Chop with Band",
            "Incline Bench Press",
            "Incline Dumbbell Curl",
            "Incline Dumbbell Press",
            "Incline Push-Up",
            "Inverted Row",
            "Inverted Row with Underhand Grip",
            "Jefferson Curl",
            "Kettlebell Swing",
            "Kneeling Ab Wheel Roll-Out",
            "Kneeling Incline Push-Up",
            "Kneeling Plank",
            "Kneeling Push-Up",
            "Kneeling Side Plank",
            "Landmine Hack Squat",
            "Landmine Squat",
            "Lat Pulldown (Iso-Lateral)",
            "Lat Pulldown (Pronated Grip)",
            "Lat Pulldown (Supinated Grip)",
            "Lateral Walk With Band",
            "Leg Extension",
            "Leg Press (Seated)",
            "Leg Press (45 Degrees Plated)",
            "Lying Dumbbell External Shoulder Rotation",
            "Lying Dumbbell Internal Shoulder Rotation",
            "Lying Leg Curl",
            "Lying Leg Raise",
            "Lying Windshield Wiper",
            "Lying Windshield Wiper with Bent Knees",
            "Machine Bicep Curl",
            "Machine Chest Fly",
            "Machine Chest Press (Horizontal)",
            "Machine Chest Press (Iso-Lateral)",
            "Machine Crunch",
            "Machine Glute Kickbacks",
            "Machine Lateral Raise",
            "Machine Shoulder Press",
            "Monkey Row",
            "Mountain Climbers",
            "Oblique Crunch",
            "Oblique Sit-Up",
            "One-Handed Bar Hang",
            "One-Handed Cable Row",
            "One-Handed Lat Pulldown",
            "One-Legged Glute Bridge",
            "One-Legged Hip Thrust",
            "Overhead Cable Triceps Extension",
            "Overhead Press",
            "Pause Deadlift",
            "Pause Squat",
            "Pec Deck",
            "Pendlay Row",
            "Plank",
            "Plate Front Raise",
            "Plate Pinch",
            "Plate Wrist Curl",
            "Power Clean",
            "Power Jerk",
            "Power Snatch",
            "Pull-Up",
            "Push Press",
            "Push-Up",
            "Push-Up Against Wall",
            "Push-Ups With Feet in Rings",
            "Rack Pull",
            "Resistance Band Chest Fly",
            "Reverse Cable Flyes",
            "Reverse Dumbbell Flyes",
            "Reverse Machine Fly",
            "Romanian Deadlift",
            "Safety Bar Squat",
            "Seal Row",
            "Seated Barbell Overhead Press",
            "Seated Calf Raise",
            "Seated Dumbbell Shoulder Press",
            "Seated Leg Curl",
            "Seated Machine Row",
            "Seated Smith Machine Shoulder Press",
            "Shallow Body Weight Lunge",
            "Side Lunges (Bodyweight)",
            "Side Plank",
            "Single Leg Romanian Deadlift",
            "Sit-Up",
            "Smith Machine Bench Press",
            "Smith Machine Incline Bench Press",
            "Smith Machine Squat",
            "Snatch",
            "Snatch Grip Behind the Neck Press",
            "Snatch Grip Deadlift",
            "Spider Curl",
            "Split Jerk",
            "Squat",
            "Squat Jerk",
            "Standing Cable Chest Fly",
            "Standing Calf Raise (Barbell)",
            "Standing Calf Raise (Smith Machine)",
            "Standing Glute Kickback in Machine",
            "Standing Resistance Band Chest Fly",
            "Step Up",
            "Stiff-Legged Deadlift",
            "Straight Arm Lat Pulldown",
            "Sumo Deadlift",
            "T-Bar Row",
            "Towel Pull-Up",
            "Trap Bar Deadlift With High Handles",
            "Trap Bar Deadlift With Low Handles",
            "Tricep Bodyweight Extension",
            "Tricep Pushdown With Bar",
            "Tricep Pushdown With Rope"
        };
    }
}
