version: '3.8'

services:
  leeklog-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=mysql-db;Port=3306;Database=leeklog;User=root;Password=TestPassword123!

  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: TestPassword123!
      MYSQL_DATABASE: leeklog
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
